# Generated by Django 3.2.13 on 2022-06-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'prof',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_list', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('apply_period', models.DateTimeField(blank=True, null=True)),
                ('limit_num', models.IntegerField(blank=True, null=True)),
                ('audit_type', models.TextField()),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ProfApp.subject')),
            ],
            options={
                'db_table': 'unit',
                'managed': True,
            },
        ),
    ]
