# Generated by Django 4.0.4 on 2022-05-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'prof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('subject_id', models.IntegerField()),
                ('apply_period', models.DateTimeField()),
                ('limit_num', models.IntegerField()),
                ('audit_type', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
    ]
