# Generated by Django 3.2.13 on 2022-06-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
            ],
            options={
                'db_table': 'stud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.BooleanField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProfApp.subject')),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('admim_mileage', models.IntegerField()),
                ('apply_time', models.DateTimeField()),
                ('remain_semaster', models.IntegerField()),
                ('result', models.BooleanField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudApp.stud')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProfApp.unit')),
            ],
            options={
                'db_table': 'apply',
                'managed': True,
            },
        ),
    ]
