# Generated by Django 3.2.13 on 2022-06-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='admim_mileage',
            new_name='admin_mileage',
        ),
    ]
