# Generated by Django 3.2.13 on 2022-06-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfApp', '0001_initial'),
        ('StudApp', '0002_rename_admim_mileage_apply_admin_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='remain_semaster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='result',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='StudApp.stud'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ProfApp.unit'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ProfApp.subject'),
        ),
    ]
